-- MySQL Script generated by MySQL Workbench
-- Thu Nov 21 19:49:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema a2023951431@teiacoltec.org
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema a2023951431@teiacoltec.org
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `a2023951431@teiacoltec.org` DEFAULT CHARACTER SET utf8 ;
USE `a2023951431@teiacoltec.org` ;

-- -----------------------------------------------------
-- Table `a2023951431@teiacoltec.org`.`prova_estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a2023951431@teiacoltec.org`.`prova_estabelecimento` (
  `cnpj` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a2023951431@teiacoltec.org`.`prova_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a2023951431@teiacoltec.org`.`prova_usuario` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(9) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a2023951431@teiacoltec.org`.`prova_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a2023951431@teiacoltec.org`.`prova_compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `cpf_usuario` VARCHAR(11) NOT NULL,
  `cnpj_estabelecimento` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compra_usuario_idx` (`cpf_usuario` ASC) VISIBLE,
  INDEX `fk_compra_estabelecimento1_idx` (`cnpj_estabelecimento` ASC) VISIBLE,
  CONSTRAINT `fk_compra_usuario`
    FOREIGN KEY (`cpf_usuario`)
    REFERENCES `a2023951431@teiacoltec.org`.`prova_usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_estabelecimento1`
    FOREIGN KEY (`cnpj_estabelecimento`)
    REFERENCES `a2023951431@teiacoltec.org`.`prova_estabelecimento` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
